meta_product_name: "Buddy Gaming"
meta_title: "Buddy Gaming - Come find your Buddy Gaming !"
meta_description: "You want to play and meet some new people, this application is made for you !
Come and discover new people with the same interest as you !"
meta_image: '/images/logo_bg2.png'
